import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import "../assets/styles/globals.css";
import TopNavBar from "../components/TopNavBar";
import Footer from "../components/Footer";

const cabin = Cabin({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cabin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cabin.variable}>
      <body className="font-cabin">
        <TopNavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
